[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[window]
opacity = 0.75
decorations = "none"

[window.padding]
x = 2
y = 5

[font]
size = 10.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hack Nerd Font Mono, Bold"
style = "Bold"

[font.italic]
family = "Hack Nerd Font Mono, Regular Italic"
style = "Italic"

[font.bold_italic]
family = "Hack Nerd Font Mono, Bold Italic"
style = "Bold Italic"
